name: Build and Release APK

on:
  push:
    branches:
      - main

env:
  ANDROID_HOME: /usr/local/android-sdk
  JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: yarn install

    - name: Build APK
      run: chmod +x android/gradlew && npx react-native run-android --variant=release

    - name: Upload APK to GitHub Release
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/release/app-release.apk
